# Generated by Django 2.2 on 2022-03-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
                ('book_image', models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.adaz                                                           ing.com%2Fbook-clipart%2F&psig=AOvVaw37fn8OKIhIpRhrZSqzkkCr                                                           &ust=1647469645901000&source=images&cd=vfe&ved=0CAsQjRxqFwoT                                                           CNjp3-qUyfYCFQAAAAAdAAAAABAD', max_length=500)),
            ],
        ),
    ]
